//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameOfWords.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameOfWords.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the
        ///of
        ///and
        ///to
        ///a
        ///in
        ///for
        ///is
        ///on
        ///that
        ///by
        ///this
        ///with
        ///i
        ///you
        ///it
        ///not
        ///or
        ///be
        ///are
        ///from
        ///at
        ///as
        ///your
        ///all
        ///have
        ///new
        ///more
        ///an
        ///was
        ///we
        ///will
        ///home
        ///can
        ///us
        ///if
        ///page
        ///my
        ///has
        ///free
        ///but
        ///our
        ///one
        ///do
        ///no
        ///time
        ///they
        ///site
        ///he
        ///up
        ///may
        ///what
        ///news
        ///out
        ///use
        ///any
        ///see
        ///only
        ///so
        ///his
        ///when
        ///here
        ///who
        ///web
        ///also
        ///now
        ///help
        ///get
        ///pm
        ///view
        ///c
        ///e
        ///am
        ///been
        ///how
        ///were
        ///me
        ///s
        ///some
        ///its
        ///like
        ///x
        ///than
        ///find
        ///date
        ///back
        ///top
        ///had
        ///list
        ///name
        ///just
        ///over
        ///year
        ///day
        ///into
        ///two
        ///n
        ///re
        ///next
        ///used
        ///go
        ///b
        ///work
        ///last
        ///most
        ///buy
        ///data
        ///make
        ///them
        ///post
        ///her
        ///city
        ///t
        ///add
        ///such
        ///best
        ///then
        ///jan
        ///good
        ///well
        ///d
        ///info
        ///high
        ///m
        ///each
        ///she
        ///ve [rest of string was truncated]&quot;;.
        /// </summary>
        public static string easy {
            get {
                return ResourceManager.GetString("easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information
        ///available
        ///copyright
        ///university
        ///management
        ///international
        ///development
        ///education
        ///community
        ///technology
        ///following
        ///resources
        ///including
        ///directory
        ///government
        ///department
        ///description
        ///insurance
        ///different
        ///categories
        ///conditions
        ///accessories
        ///september
        ///questions
        ///application
        ///financial
        ///equipment
        ///performance
        ///experience
        ///important
        ///activities
        ///additional
        ///something
        ///professional
        ///committee
        ///washington
        ///california
        ///reference
        ///companies
        ///computers
        ///president
        ///australia
        ///discussion
        ///entertainment
        ///agreement
        ///marketing
        ///association
        ///coll [rest of string was truncated]&quot;;.
        /// </summary>
        public static string hard {
            get {
                return ResourceManager.GetString("hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about
        ///search
        ///other
        ///which
        ///their
        ///there
        ///contact
        ///business
        ///online
        ///first
        ///would
        ///services
        ///these
        ///click
        ///service
        ///price
        ///people
        ///state
        ///email
        ///health
        ///world
        ///products
        ///music
        ///should
        ///product
        ///system
        ///policy
        ///number
        ///please
        ///support
        ///message
        ///after
        ///software
        ///video
        ///where
        ///rights
        ///public
        ///books
        ///school
        ///through
        ///links
        ///review
        ///years
        ///order
        ///privacy
        ///items
        ///company
        ///group
        ///under
        ///general
        ///research
        ///january
        ///reviews
        ///program
        ///games
        ///could
        ///great
        ///united
        ///hotel
        ///center
        ///store
        ///travel
        ///comments
        ///report
        ///member
        ///details
        ///terms
        ///before
        ///hotels
        ///right
        ///because
        ///local
        ///those
        ///using
        ///re [rest of string was truncated]&quot;;.
        /// </summary>
        public static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
    }
}
